# action.yml
name: 'Custom Github Status'
description: 'GitHub action to create custom status'
branding:
  icon: 'check-square'
  color: 'black'
runs:
  using: 'docker'
  image: 'docker://geekodour/ghcs:0.0.4'